name: Drift Detection

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:

jobs:
  drift-detection:
    name: Check for Infrastructure Drift
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Terraform Init
        working-directory: ./environments/${{ matrix.environment }}
        run: terraform init -backend-config=backend.conf

      - name: Check for Drift
        working-directory: ./environments/${{ matrix.environment }}
        run: |
          terraform plan -detailed-exitcode -out=drift-check.plan
          exit_code=$?
          if [ $exit_code -eq 2 ]; then
            echo "DRIFT_DETECTED=true" >> $GITHUB_ENV
            echo "Drift detected in ${{ matrix.environment }} environment!"
          fi

      - name: Create Issue on Drift
        if: env.DRIFT_DETECTED == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Infrastructure Drift Detected - ${{ matrix.environment }}`,
              body: `Drift has been detected in the ${{ matrix.environment }} environment. Please review and remediate.`,
              labels: ['infrastructure', 'drift', '${{ matrix.environment }}']
            })
