name: Terraform Apply
on:
  push:
    branches: [ main ]
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: List files
        run: ls -al environments/dev
      - name: Terraform Init and Apply
        working-directory: environments/dev
        run: |
             terraform init -backend-config=backend.conf
             terraform apply -auto-approve
             
  terraform-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.2'
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: environments/dev
      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev
        
  terratest:
    needs: terraform-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Use Go version compatible with Terratest
      
      - name: Initialize Go Modules
        run: |
          cd tests/unit
          go mod init github.com/yourusername/terraform-iac-framework
          go mod tidy
      
      - name: Run Terratest Unit Tests
        run: |
          cd tests/unit
          go test -v
