name: Terraform Apply
on:
  push:
    branches: [ main ]
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: List files
        run: ls -al environments/dev

      - name: Terraform Init and Apply
        working-directory: environments/dev
        run: |
             terraform init -backend-config=backend.conf
             terraform apply -auto-approve
