name: Terraform CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-validate:
    name: Terraform Format, Init and Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init -backend-config=backend.conf
      working-directory: environments/dev

    - name: Format Check
      run: terraform fmt -check
      working-directory: environments/dev

    - name: Validate Configuration
      run: terraform validate
      working-directory: environments/dev


  terraform-apply:
    name: Terraform Apply
    needs: terraform-validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: List environment files
        run: ls -al environments/dev
        working-directory: .

      - name: Terraform Init and Apply
        working-directory: environments/dev
        run: |
          terraform init -backend-config=backend.conf
          terraform apply -auto-approve

  terratest:
    name: Terratest Unit Tests
    needs: terraform-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Initialize Go Modules and Run Tests
        run: |
          cd tests/unit
          go mod init github.com/AshokNaidu-Code/terraform-iac-framework
          go mod tidy
          go test -v
