name: Terraform Check
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/**'
      - 'environments/**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Format Check
        run: terraform fmt -check
      - name: Validate
        run: terraform validate -no-color
      - name: Plan
        run: terraform plan -no-color
